---
# cleanup-k3s.yml
- name: Remover completamente o cluster K3s
  hosts: all
  become: true
  tasks:
    - name: Parar e desabilitar o serviço keepalived
      systemd:
        name: keepalived
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Parar e remover o K3s em master
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes
      when: inventory_hostname in groups['master']

    - name: Parar e remover o K3s-agent em workers
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
      when: inventory_hostname in groups['workers']

    - name: Remover diretórios K3s
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /var/lib/rancher
        - /etc/keepalived

    - name: Remover dados persistentes do Pi-hole
      file:
        path: /data/pihole
        state: absent
      ignore_errors: yes

    - name: Remover diretório de configuração do Keepalived
      file:
        path: /etc/keepalived
        state: absent
      ignore_errors: yes

    - name: Remover arquivos kubeconfig
      file:
        path: /root/.kube
        state: absent
      ignore_errors: yes

    - name: Remover o IP virtual das interfaces
      shell: ip addr del {{ virtual_ip }}/24 dev eth0
      ignore_errors: yes

    - name: Reiniciar todos os nós
      reboot:
