---
# cleanup-k3s.yml
- name: Remover completamente o cluster K3s
  hosts: all
  become: true
  tasks:
    - name: Parar e desabilitar o serviço keepalived
      systemd:
        name: keepalived
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Parar e remover o K3s em todos os nós
      shell: /usr/local/bin/k3s-uninstall.sh
      ignore_errors: yes

    - name: Parar e remover o K3s-agent em nós worker
      shell: /usr/local/bin/k3s-agent-uninstall.sh
      ignore_errors: yes
      when: inventory_hostname in groups['workers']

    - name: Remover diretórios K3s
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/rancher
        - /var/lib/rancher
        - /var/lib/kubelet
        - /etc/keepalived

    - name: Remover dados persistentes do Pi-hole
      file:
        path: /data/pihole
        state: absent
      ignore_errors: yes

    - name: Remover diretório de configuração do Keepalived
      file:
        path: /etc/keepalived
        state: absent
      ignore_errors: yes

    - name: Remover arquivos kubeconfig
      file:
        path: /root/.kube
        state: absent
      ignore_errors: yes

    - name: Reativar swap no fstab
      replace:
        path: /etc/fstab
        regexp: '^# (.*?\sswap\s+sw\s+.*)$'
        replace: '\1'
      ignore_errors: yes

    - name: Remover parâmetros cgroup do boot
      lineinfile:
        path: /boot/cmdline.txt
        regexp: 'cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        state: absent
      ignore_errors: yes

    - name: Remover o IP virtual das interfaces
      shell: ip addr del {{ virtual_ip }}/24 dev eth0
      ignore_errors: yes

    - name: Reiniciar todos os nós
      reboot:
        reboot_timeout: 3600
