---
- name: Configurar nós master e worker
  hosts: all
  become: true
  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar dependências
      apt:
        name:
          - curl
          - iptables
          - nftables
          - keepalived
        state: present

    - name: Configurar hostname
      hostname:
        name: "{{ inventory_hostname }}"

- name: Configurar master K3s
  hosts: master
  become: true
  tasks:
    - name: Instalar K3s no master
      shell: |
        curl -sfL https://get.k3s.io | sh -s - server \
          --token={{ k3s_token }} \
          --disable traefik \
          --disable servicelb \
          --flannel-backend=host-gw \
          --kube-controller-manager-arg="bind-address=0.0.0.0" \
          --kube-scheduler-arg="bind-address=0.0.0.0" \
          --kube-proxy-arg="metrics-bind-address=0.0.0.0" \
          --node-taint "node-role.kubernetes.io/master=effect:NoSchedule"
      args:
        creates: /usr/local/bin/k3s

    - name: Esperar K3s iniciar
      wait_for:
        path: /etc/rancher/k3s/k3s.yaml
        delay: 5
        timeout: 300

    - name: Obter kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ./kubeconfig
        flat: yes

    - name: Garantir que a pasta /etc/keepalived exista
      file:
        path: /etc/keepalived
        state: directory
        mode: '0755'

    - name: Configurar keepalived (master)
      template:
        src: keepalived-master.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: Reiniciar keepalived

  handlers:
    - name: Reiniciar keepalived
      service:
        name: keepalived
        state: restarted
        enabled: yes

- name: Configurar workers K3s
  hosts: workers
  become: true
  tasks:
    - name: Instalar K3s worker
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['k3s-master']['ansible_host'] }}:6443 K3S_TOKEN={{ k3s_token }} sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Garantir que a pasta /etc/keepalived exista
      file:
        path: /etc/keepalived
        state: directory
        mode: '0755'

    - name: Configurar keepalived (worker)
      template:
        src: keepalived-backup.conf.j2
        dest: /etc/keepalived/keepalived.conf
      notify: Reiniciar keepalived

  handlers:
    - name: Reiniciar keepalived
      service:
        name: keepalived
        state: restarted
        enabled: yes
