---
# cleanup-pihole.yml
- name: Remover implantação do Pi-hole do cluster K3s
  hosts: master
  become: true
  tasks:
    - name: Verificar se o namespace pihole existe
      shell: kubectl get namespace pihole
      register: pihole_namespace
      failed_when: false
      changed_when: false

    - name: Remover serviço Pi-hole
      shell: kubectl delete service pihole -n pihole
      when: pihole_namespace.rc == 0
      ignore_errors: yes

    - name: Remover deployment do Pi-hole
      shell: kubectl delete deployment pihole -n pihole
      when: pihole_namespace.rc == 0
      ignore_errors: yes

    - name: Remover PersistentVolumeClaim do Pi-hole
      shell: kubectl delete pvc pihole-data -n pihole
      when: pihole_namespace.rc == 0
      ignore_errors: yes

    - name: Remover ConfigMap do Pi-hole
      shell: kubectl delete configmap pihole-config -n pihole
      when: pihole_namespace.rc == 0
      ignore_errors: yes

    - name: Remover namespace pihole
      shell: kubectl delete namespace pihole
      when: pihole_namespace.rc == 0
      ignore_errors: yes

    - name: Remover PersistentVolume do Pi-hole
      shell: kubectl delete pv pihole-data
      ignore_errors: yes

    - name: Limpar diretório de dados do Pi-hole no nó master
      file:
        path: /data/pihole
        state: absent
      ignore_errors: yes

    - name: Remover arquivos de manifests do Pi-hole
      file:
        path: /root/k3s-manifests/{{ item }}
        state: absent
      with_items:
        - 01-pihole-namespace.yaml
        - 02-pihole-configmap.yaml
        - 04-pihole-pv.yaml
        - 05-pihole-pvc.yaml
        - 06-pihole-deployment.yaml
        - 09-pihole-service.yaml
      ignore_errors: yes
