---
- name: Configurar sistema, instalar/remover pacotes, ajustar serviços e modificar cmdline.txt
  hosts: all
  become: yes

  vars:
    list01:
      - net-tools
      - speedtest-cli
      - whois
      - netdiscover
      - iperf
      - arp-scan
      - traceroute
      - sshpass
      - zip
      - unzip
      - p7zip-full
      - 7zip
      - p7zip
      - cifs-utils
      - iotop
      - btop
      - tree
      - dialog
      - build-essential
      - unrar
      - curl

    packages_to_remove:
      - needrestart
      - cloud-init
      - snapd
      - unattended-upgrades
      - plank
      - deja-dup
      - evolution
      - evolution-data-server
      - bluez
      - blueman
      - bluetooth
      - docker.io
      - avahi-daemon
      - lvm2
      - update-notifier-common
      - apport
      - apport-symptoms
      - wpasupplicant
      - apparmor
      - ufw
      - network-manager

    kernel_parameters:
      - "kernel.sysrq=1"
      - "vm.panic_on_oom=1"
      - "vm.swappiness=10"
      - "kernel.panic=5"
      - "#net.ipv4.ip_forward=1"
      - "#net.ipv6.conf.all.disable_ipv6=1"
      - "#net.ipv6.conf.default.disable_ipv6=1"

  tasks:
    - name: Atualizar os repositórios de pacotes inicialmente
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Remover pacotes desnecessários
      apt:
        name: "{{ packages_to_remove }}"
        state: absent
        purge: yes

    - name: Autoremove pacotes não necessários
      apt:
        autoremove: yes

    - name: Atualizar os repositórios de pacotes após remoção
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Atualizar o sistema após remoção dos pacotes
      apt:
        upgrade: dist
        state: latest

    - name: Instalar pacotes
      apt:
        name: "{{ list01 }}"
        state: present

    - name: Configurar fuso horário
      shell: |
        sudo timedatectl set-timezone Etc/GMT+3
        sudo timedatectl set-local-rtc 1

    - name: Desativar e mascarar o serviço systemd-networkd-wait-online
      shell: |
        sudo systemctl disable systemd-networkd-wait-online.service
        sudo systemctl mask systemd-networkd-wait-online.service

    - name: Adicionar parâmetros ao /etc/sysctl.conf
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
        state: present
      loop: "{{ kernel_parameters }}"

    - name: Ativar cgroup
      lineinfile:
        path: /boot/firmware/cmdline.txt
        regexp: '^(.*)$'
        line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
        backrefs: yes

    - name: Desativar e mascar os timers e serviços apt-daily e e2scrub
      shell: |
        sudo systemctl disable apt-daily.timer apt-daily-upgrade.timer e2scrub
        sudo systemctl mask apt-daily.timer apt-daily-upgrade.timer e2scrub
        sudo systemctl disable e2scrub_all.timer e2scrub_reap.service
        sudo systemctl mask e2scrub_all.timer e2scrub_reap.service
